name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '?? Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '?? Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '?? Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '?? Documentation'
    labels:
      - 'documentation'
  - title: '?? Security'
    labels:
      - 'security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'
      - 'security'
  default: patch
template: |
  ## What's Changed

  $CHANGES

  ## New Contributors
  $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## Docker Images
  
  ```bash
  docker pull ghcr.io/$OWNER/$REPOSITORY/accounting-api:v$RESOLVED_VERSION
  ```

  ## Installation
  
  ```bash
  # Clone the repository
  git clone https://github.com/$OWNER/$REPOSITORY.git
  cd $REPOSITORY
  
  # Checkout this version
  git checkout v$RESOLVED_VERSION
  
  # Build and run
  dotnet build
  dotnet run --project src/Accounting.Api
  ```