name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Build and test
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet test --configuration Release
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Build and push versioned Docker image
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}/accounting-api
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build -t $REGISTRY/$IMAGE_NAME:${{ github.ref_name }} -f src/Accounting.Api/Dockerfile .
        docker push $REGISTRY/$IMAGE_NAME:${{ github.ref_name }}